# roles/drupal/tasks/main.yml
---

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: drupal

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ drupal_packages }}"
  tags: drupal

- name: Ensure service is started
  service:
    name: "{{ drupal_service }}"
    state: started
    enabled: true
  tags: drupal
